### ISSUE TITLE
throw error

### ISSUE THREAD

**Issue by alexkoveos** [raymasaki/supermassive#2]
@jasonseminara @amcooper @zhenpanda @WilliamfShaw

Hey so I have a throw error that doesnt seem to go away and wont be solved by kill alls

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Listening on port 3000...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/alexkoveos/Desktop/supermassive/supermassive/testing/front_end_test/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at null.<anonymous> (/Users/alexkoveos/Desktop/supermassive/supermassive/testing/front_end_test/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/alexkoveos/Desktop/supermassive/supermassive/testing/front_end_test/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by WilliamfShaw** [comment]
Do some more research..... All I did was google the error directly

http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson

**Comment by WilliamfShaw** [comment]
@alexkoveos ^ ^ ^ ^ ^ ^
